const ProductData=[
    {
        "id":1,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/71r49yCHtkL._SY741_.jpg"
    },
    {
        "id":2,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/71KnbCtJT6L._SX679_.jpg"
    },
    {
        "id":3,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/41+xBrKwHiL.jpg"
    },
    {
        "id":4,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/71I+Dl45TGL._SY741_.jpg"
    },
    {
        "id":5,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/71GbSWIv27L._SY741_.jpg"
    },
    {
        "id":6,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/51kVjyJgVML._SY741_.jpg"
    },
    {
        "id":7,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/61p80o+58PL._SX679_.jpg"
    },
    {
        "id":8,
        "name":"mobile",
        "brand":"oppo",
        "price":9800,
        "images":"https://m.media-amazon.com/images/I/61RVJ1RwrYL._SX679_.jpg"
    },
    
]

export default ProductData;